apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello
  name: hello
spec:
  containers:
  - image: 192.168.0.195:5000/sryteacher:hello
    name: hello
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: hello-svc
spec:
  selector:
    name: hello
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
~                   
